spring:
  datasource:
    url: jdbc:mysql://localhost:3306/kopidlno?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

server:
  port: 10563

smartform:
  url: https://www.smartform.cz/download/kopidlno.xml.zip
